### ISSUE TITLE
cant get raspberrypi.local/setup to work

### ISSUE THREAD

**Issue by welshlamb10** [cortictechnology/cep#35]
I've followed the instructions line by line. I've also installed fresh RaspberryPi sketch onto the SD card two times.
I get as far as visiting raspberrypi.local/setup 

Then I get the error: 
This site can’t be reachedCheck if there is a typo in raspberrypi.local.
DNS_PROBE_FINISHED_NXDOMAIN

This happens on both the pi itself and when trying to access on any other machine on the network.
I'm using DECO mesh WI-FI (not sure if this is impacting it). I've tried ethernet cable direct to router, with no difference.

Appreciate help getting this sorted.

**Comment by michaelhwn** [comment]
Hi @welshlamb10, I will need to know a bit more information regarding your setup:

1. What is the operating system of the computer that you use to access the Pi? 
2. What is the browser that you use? 
3. Are you using a Raspberry Pi 4?
4. What is the version of the operating system you installed on the Pi?
5. Have you changed the hostname when you were in raspberrypi.local/setup?

**Comment by af1964** [comment]
Hi,
have same issue. 
OS raspios bullseyes - arm64
Try to connect with firefox and edge on  Windows 11 machine
ping raspberrypi.local - works
use Pi 4 8Go with usb 64 Go new installation

Regards

André Forys

**Comment by af1964** [comment]
After some investigations, it seems to be the flask version and Jnija2 new version problem can't find 'escape' the server is not running.

**Comment by af1964** [comment]
Hi,

I removed the flask version in usr/lib/python3. Lauch a new setup. The server begins to work (localhost/setup). But the second site page never progress.
lsusb found the camera.
This is the log :
déc. 26 01:01:26 raspberrypi systemd[1]: Started CAIT Webapp service.
déc. 26 01:01:32 raspberrypi bash[461]:  * Serving Flask app 'main'
déc. 26 01:01:32 raspberrypi bash[461]:  * Debug mode: off
déc. 26 01:01:32 raspberrypi bash[461]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
déc. 26 01:01:32 raspberrypi bash[461]:  * Running on all addresses (0.0.0.0)
déc. 26 01:01:32 raspberrypi bash[461]:  * Running on http://127.0.0.1:80
déc. 26 01:01:32 raspberrypi bash[461]:  * Running on http://127.0.0.1:80
déc. 26 01:01:32 raspberrypi bash[461]: Press CTRL+C to quit
déc. 26 01:01:32 raspberrypi bash[461]: INFO:root:BaseCommand: Port 9433 is available
déc. 26 01:01:33 raspberrypi bash[461]: Exception in thread Thread-1:
déc. 26 01:01:33 raspberrypi bash[461]: Traceback (most recent call last):
déc. 26 01:01:33 raspberrypi bash[461]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
déc. 26 01:01:33 raspberrypi bash[461]:     self.run()
déc. 26 01:01:33 raspberrypi bash[461]:   File "/usr/lib/python3.9/threading.py", line 892, in run
déc. 26 01:01:33 raspberrypi bash[461]:     self._target(*self._args, **self._kwargs)
déc. 26 01:01:33 raspberrypi bash[461]:   File "/home/af/cep/src/cait/cortic_webapp/main.py", line 107, in import_cait_modules
déc. 26 01:01:33 raspberrypi bash[461]:     from cait import essentials
déc. 26 01:01:33 raspberrypi bash[461]:   File "/home/af/cep/src/cait/cait/essentials.py", line 8, in <module>
déc. 26 01:01:33 raspberrypi bash[461]:     import cait.core as core
déc. 26 01:01:33 raspberrypi bash[461]:   File "/home/af/cep/src/cait/cait/core.py", line 23, in <module>
déc. 26 01:01:33 raspberrypi bash[461]:     import cv2
déc. 26 01:01:33 raspberrypi bash[461]: ModuleNotFoundError: No module named 'cv2'
I installed cv2 opencv-python and run again setup. Doesn't work. (I did it with another installation so I don't have the log it lakes a type package. Can't do more for now.

Regards

André Forys

**Comment by michaelhwn** [comment]
Hi @af1964, I believe the problem is caused by a failed setup process. I would need to update the setup script to resolve any conflicts or failures caused by the latest updates to the OS or dependent software packages. I will let you know once I have updated the setup script.

**Comment by af1964** [comment]
Hi, 

 

What I did : remove Flask from de raspi during installation it finds the default installation and do nothing for Flask 

I downgrade a package jinja2 == 3.0.3

I tried to build a new package for opencv-python-contrib because it lakes Freetype (not really found a solution)

Retrieve a version of opencv_contrib_python==4.4.0.46 with  Freetype included (in process I’ll see result this evening)

 

Regards

 

 

 

De : michaelhwn ***@***.***> 
Envoyé : mardi 3 janvier 2023 18:07
À : cortictechnology/cep ***@***.***>
Cc : af1964 ***@***.***>; Mention ***@***.***>
Objet : Re: [cortictechnology/cep] cant get raspberrypi.local/setup to work (Issue #35)

 

Hi @af1964 <https://github.com/af1964> , I believe the problem is caused by a failed setup process. I would need to update the setup script to resolve any conflicts or failures caused by the latest updates to the OS or dependent software packages.

**Comment by dhruvmsheth** [comment]
@af1964 were you able to resolve it? I'm facing the same issue

**Comment by dhruvmsheth** [comment]
@michaelhwn what would be the most stable OS version for running CEP? Looks like 64 bit doesn't work with robot inventor and neither does 32 bit seem like. The flask 'escape' error seems persistent.

**Comment by robofan69** [comment]
@michaelhwn I have the same issue, any update on that issue. Try twice to do a complet new installation from the scratch but can't get  http://xxx.local/setup to run. I get always Err_Connection_refused at the browser. I'm running standard 32 bit OS Version (recommend OS Version from Raspberry installer. For your support in advance many thanks. I must admit I'm not an expert in Raspberry itself or debian
When I execute start_cait.sh I get: ImportError cannot import name "escape" from "jinja2"

**Comment by robofan69** [comment]
@michaelhwn I have the same issue, any update on that issue. Try twice to do a complet new installation from the scratch following the instructions but can't get  http://xxx.local/setup to running. I'm running standard 32 bit OS Version (recommend OS Version from Raspberry installer. For your support in advance many thanks.

**Comment by robofan69** [comment]
@michaelhwn OK now I try several optionss- 
1. Clean installation raspberry pi
2. New setup CEP
3. Downgrade jinja2 > 3.1.0 --> 3.0.3 or even earlier version no change error persist
4. update Flask 2.1.2 -> no change error persist.

Meanwhile I really don't know what else I can test or change. I would be more then appreciated for any feedback or help.
For your support in advance many thanks
